// Generated by scripts/generate-reference.ts; do not edit.
export const COMMAND_REFERENCE = `## Command syntax

Prefix each row with \`mc-agent\` (or the harness wrapper). \`<…>\` needs a value; \`[…]\` is optional. Literal values in optional arguments are defaults; replace them as needed. Boolean defaults and allowed values are described below. Quote text containing spaces/newlines. Internal \`daemon\` commands are omitted; \`advanced\` is included.

- Globals: \`--output json|text\`, \`--client <id>\`, \`--strict-context\`, \`--version\`, \`--help\`. Client defaults to \`MC_AGENT_CLIENT_ID\`; strict mode also accepts \`MC_AGENT_STRICT_CONTEXT=true\`.
- All rows except \`session list\` / \`skills get\` accept \`[--session default]\`; a harness may select another session.
- \`*\` marks context-gated commands: \`[--context <context>]\` or \`[--runtime <runtimeId> --world-epoch <epoch>]\`, otherwise saved client context; \`[--no-observe]\` omits the attached frame.
- \`*\` rows also accept \`[--wait [ms]]\` (bare flag = 5000, range 0–30000), except \`navigate configure\`, \`advanced navigate-configure\`, and \`action stop\`. Those apply immediately; cancel also returns immediately. Continuous actions return after start regardless of wait.

\`\`\`text
  session start [--host localhost] [--port 25565] [--username AgentBot] [--auth offline] [--minecraft-version <version>] [--listen] [--no-listen] [--auto-reconnect] [--no-auto-reconnect] [--detail <detail>] [--reconnect-max-attempts <count>] [--reconnect-backoff <ms>]
  session status [--detail <detail>]
  session list [--detail <detail>]
  session stop
  session ensure-ready [--timeout 10000] [--max-attempts 3] [--backoff 250]

  observe surroundings [--range 32] [--detail] [--bounds <min:max>]
  observe frame [--since <frame>] [--detail compact] [--max-entities 12] [--radius 64] [--track <track>]
  observe events [--since 0] [--profile all] [--limit 50] [--type <eventType>]
  observe watch [--exclude-self] [--since 0] [--profile all] [--type <eventType>] [--track <track>] [--fields <fields>] [--rate <hz>]

  chat listen [--since now] [--include-self]
  chat send --message <text> [--allow-command]
  chat whisper --username <name> --message <text>
  chat tab-complete --text <text> [--assume-command] [--send-block-in-sight] [--timeout 5000]

  bot players
  bot tablist
  bot scoreboards
  bot teams

* control tap --state <state> [--duration-ms 500]
* control set --state <state> [--value] [--off]

* look at --x <number> --y <number> --z <number>
* look track --track <track>

* navigate goto --x <number> --y <number> --z <number> [--range 1]
* navigate approach --track <track> [--range 2] [--best-effort]
* navigate follow --track <track> [--range 2]
* navigate configure [--allow-dig] [--allow-place] [--no-place] [--no-dig] [--allow-sprinting] [--no-sprinting] [--allow-parkour] [--no-parkour] [--can-open-doors] [--max-drop-down <blocks>]

* collect item --track <track> [--range 1]

* inventory equip --item <name> [--destination hand]
* inventory unequip [--destination hand]
* inventory quickbar --slot <0-8>
* inventory toss --item <name> [--count 1]
* inventory consume
* inventory fish
* inventory activate-item [--offhand]
  inventory recipes --item <name> [--count 1] [--table-x <number>] [--table-y <number>] [--table-z <number>]
* inventory craft --item <name> [--count 1] [--table-x <number>] [--table-y <number>] [--table-z <number>] [--recipe-index <index>] [--recipe-id <id>]

  world block --x <number> --y <number> --z <number>
  world block-at-cursor [--max-distance 5]
  world find-blocks --name <name> [--radius 32] [--count 10]
* world dig --x <number> --y <number> --z <number>
* world place --x <number> --y <number> --z <number> [--face up] [--item <name>]
* world place-entity --x <number> --y <number> --z <number> [--face up] [--item <name>]
* world activate --x <number> --y <number> --z <number>
* world update-sign --x <number> --y <number> --z <number> --text <text> [--back]
* world sleep --x <number> --y <number> --z <number>
* world wake
* world elytra-fly

* window open-block --x <number> --y <number> --z <number>
* window open-entity --track <track>
* window deposit --item <name> [--count 1]
* window withdraw --item <name> [--count 1]
* window close

  entity find [--name <name>] [--types <species>] [--radius 32] [--limit 50]
  entity inspect --track <track>
* entity interact --track <track>
* entity attack --track <track> [--allow-players] [--allow-passive]
* entity mount --track <track>
* entity dismount
* entity move-vehicle [--left 0] [--forward 0]

* action stop [--resource <resource>]
  action status --action <action>
  action wait --action <action> [--timeout 5000] [--no-observe]
* action cancel --action <action>

  debug session
  debug events [--id <id>]

  skills get <name> [--full]

* advanced look --yaw <radians> --pitch <radians> [--force]
* advanced navigate-configure [--search-radius <blocks>] [--think-timeout <ms>] [--tick-timeout <ms>]
* advanced window-click --slot <slot> [--mouse-button 0] [--mode 0]
\`\`\``;
