import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { Command, Option } from "commander";
import { buildProgram } from "../src/cli/program.js";
import type { CliHandlers } from "../src/cli/handlers.js";
import { FULL_REFERENCE, getSkillContent } from "../src/core/skills.js";

const common = new Set(["--session", "--context", "--runtime", "--world-epoch", "--wait", "--no-observe"]);

function optionSyntax(option: Option): string {
  let syntax = option.flags.replace(/^-[^,]+, /, "");
  const value = option.defaultValue;
  if ((option.required || option.optional) && value !== undefined && !Array.isArray(value)) {
    syntax = syntax.replace(/<[^>]+>|\[[^\]]+\]/, String(value));
  }
  return option.mandatory ? syntax : `[${syntax}]`;
}

/** Read parser metadata without executing handlers or starting a session. */
export function renderCommandReference(program: Command): string {
  const groups = program.commands.filter(group => group.name() !== "daemon")
    .sort((a, b) => Number(a.name() === "advanced") - Number(b.name() === "advanced"));
  const rows = groups.map(group => group.commands.map(command => {
    const physical = command.options.some(option => option.long === "--context");
    const args = command.registeredArguments.map(arg => arg.required ? `<${arg.name()}>` : `[${arg.name()}]`);
    const options = command.options.filter(option => option.long !== "--session" && (!physical || !common.has(option.long ?? "")));
    return `${physical ? "* " : "  "}${group.name()} ${command.name()} ${[...args, ...options.map(optionSyntax)].join(" ")}`.trimEnd();
  }).join("\n")).join("\n\n");

  return `## Command syntax

Prefix each row with \`mc-agent\` (or the harness wrapper). \`<…>\` needs a value; \`[…]\` is optional. Literal values in optional arguments are defaults; replace them as needed. Boolean defaults and allowed values are described below. Quote text containing spaces/newlines. Internal \`daemon\` commands are omitted; \`advanced\` is included.

- Globals: \`--output json|text\`, \`--client <id>\`, \`--strict-context\`, \`--version\`, \`--help\`. Client defaults to \`MC_AGENT_CLIENT_ID\`; strict mode also accepts \`MC_AGENT_STRICT_CONTEXT=true\`.
- All rows except \`session list\` / \`skills get\` accept \`[--session default]\`; a harness may select another session.
- \`*\` marks context-gated commands: \`[--context <context>]\` or \`[--runtime <runtimeId> --world-epoch <epoch>]\`, otherwise saved client context; \`[--no-observe]\` omits the attached frame.
- \`*\` rows also accept \`[--wait [ms]]\` (bare flag = 5000, range 0–30000), except \`navigate configure\`, \`advanced navigate-configure\`, and \`action stop\`. Those apply immediately; cancel also returns immediately. Continuous actions return after start regardless of wait.

\`\`\`text
${rows}
\`\`\``;
}

export function renderSkillFile(): string {
  return `---\nname: minecraft\ndescription: Control a live Minecraft bot through mc-agent.\n---\n\n${getSkillContent("core", false).replace("# mc-agent core", "# Minecraft")}\n`;
}

export function renderReferenceFile(syntax: string): string {
  return `# Minecraft reference\n\n<!-- Generated by scripts/generate-reference.ts; edit CLI definitions and src/core/skills.ts. -->\n\n${syntax}\n\n${FULL_REFERENCE}\n`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const program = buildProgram({} as CliHandlers, { stdout: process.stdout, stderr: process.stderr });
  const syntax = renderCommandReference(program);
  const root = new URL("../", import.meta.url);
  const literal = syntax.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");
  writeFileSync(fileURLToPath(new URL("src/core/command-reference.ts", root)),
    `// Generated by scripts/generate-reference.ts; do not edit.\nexport const COMMAND_REFERENCE = \`${literal}\`;\n`);
  writeFileSync(fileURLToPath(new URL("skills/minecraft/SKILL.md", root)), renderSkillFile());
  writeFileSync(fileURLToPath(new URL("skills/minecraft/references/playbooks.md", root)), renderReferenceFile(syntax));
}
